
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import { Poppins} from "next/font/google";
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
})
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <Navbar/>
       <main>
         {children}
       </main>
      </body>
    </html>
  );
}
